/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <UART_1.h>
#include <UART_1_SPI_UART.h>
#include <UART_1_PINS.h>
#include <UART_1_SPI_UART_PVT.h>
#include <UART_1_PVT.h>
#include <LED_GREEN.h>
#include <LED_GREEN_aliases.h>
#include <nHIB.h>
#include <nHIB_aliases.h>
#include <LED_BLUE.h>
#include <LED_BLUE_aliases.h>
#include <UARTM.h>
#include <m_cts_pin.h>
#include <m_cts_pin_aliases.h>
#include <m_rts_pin.h>
#include <m_rts_pin_aliases.h>
#include <Rx_ISR.h>
#include <UART_1_tx.h>
#include <UART_1_tx_aliases.h>
#include <UART_1_rx.h>
#include <UART_1_rx_aliases.h>
#include <UARTM_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

